version: '3'

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: words-API
      MYSQL_ROOT_PASSWORD: Super
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8888:8080"
