-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 13:52:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema words-API
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `words-API` ;

-- -----------------------------------------------------
-- Schema words-API
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `words-API` ;
USE `words-API` ;

-- -----------------------------------------------------
-- Table `words-API`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words-API`.`Team` ;

CREATE TABLE IF NOT EXISTS `words-API`.`Team` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `score` INT NULL DEFAULT NULL,
  `badge` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `words-API`.`Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words-API`.`Player` ;

CREATE TABLE IF NOT EXISTS `words-API`.`Player` (
  `id` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `score` INT NULL DEFAULT NULL,
  `pfp` BLOB NULL DEFAULT NULL,
  `Team_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Team_id`),
  INDEX `fk_Player_Equipo1_idx` (`Team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Player_Equipo1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `words-API`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `words-API`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words-API`.`Game` ;

CREATE TABLE IF NOT EXISTS `words-API`.`Game` (
  `id` INT NOT NULL,
  `Game_difficulty` ENUM('easy', 'medium', 'hard') NOT NULL,
  `max_tries` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `words-API`.`Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words-API`.`Match` ;

CREATE TABLE IF NOT EXISTS `words-API`.`Match` (
  `id` INT NOT NULL,
  `word` VARCHAR(45) NOT NULL,
  `tries` INT NOT NULL,
  `score` INT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `Player_id` INT NOT NULL,
  `Player_Team_id` INT NOT NULL,
  `Game_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Game_id`),
  INDEX `fk_Match_Player1_idx` (`Player_id` ASC, `Player_Team_id` ASC) VISIBLE,
  INDEX `fk_Match_Game1_idx` (`Game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Match_Player1`
    FOREIGN KEY (`Player_id` , `Player_Team_id`)
    REFERENCES `words-API`.`Player` (`id` , `Team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Game1`
    FOREIGN KEY (`Game_id`)
    REFERENCES `words-API`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `words-API`.`Word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words-API`.`Word` ;

CREATE TABLE IF NOT EXISTS `words-API`.`Word` (
  `id` INT NOT NULL,
  `word` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `words-API`.`Game_has_Word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words-API`.`Game_has_Word` ;

CREATE TABLE IF NOT EXISTS `words-API`.`Game_has_Word` (
  `Game_id` INT NOT NULL,
  `Word_id` INT NOT NULL,
  `wordDifficulty` ENUM('easy', 'medium', 'hard') NULL DEFAULT NULL,
  PRIMARY KEY (`Game_id`, `Word_id`),
  INDEX `fk_Game_has_Word_Word1_idx` (`Word_id` ASC) VISIBLE,
  INDEX `fk_Game_has_Word_Game_idx` (`Game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Word_Game`
    FOREIGN KEY (`Game_id`)
    REFERENCES `words-API`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Word_Word1`
    FOREIGN KEY (`Word_id`)
    REFERENCES `words-API`.`Word` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
